apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cmc-deployment-job
spec:
  schedule: "0 */1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: tiller
          containers:
            - name: cmc-deployment-job
              image: zachpuck/cmc-deploy-testing:latest
              command: [ "./deploy.sh" ]
              env:
              - name: CMA_SSH_BOOTSTRAP_IP
                value: ""
              - name: CMA_SSH_AIRGAP_PROXY_IP
                value: ""
          restartPolicy: Never
      backoffLimit: 4
