apiVersion: batch/v1
kind: Job
metadata:
  name: cmc-deployment
spec:
  template:
    spec:
      serviceAccountName: tiller
      containers:
        - name: cmc-deployment
          image: zachpuck/cmc-deploy-testing:latest
          command: [ "./deploy.sh" ]
          env:
          - name: CMA_SSH_BOOTSTRAP_IP
            value: "10.240.0.4"
          - name: CMA_SSH_AIRGAP_PROXY_IP
            value: "10.240.0.7"
      restartPolicy: Never
  backoffLimit: 4
